### ISSUE TITLE
How to set model temperature?

### ISSUE THREAD

**Issue by jarkko-hautakorpi** [Aider-AI/aider#204]
aider/sendchat.py send_with_retries() has parameter temperature=0, but how can I change this?
Can it be set in an environment variable? API call to 3.5 gives very much different answers than ChatGPT3.5, which could be due to temperature, or could it? **ChatGPT default temperature** is apparently close to **0.7** or about there.

**Comment by paul-gauthier** [comment]
Thanks for trying aider!

Can you help me understand why you want to change the temperature? Generally speaking, you want to use temp=0 to get the "best" answer, and you raise the temp to get more "creative" answers.

**Comment by jarkko-hautakorpi** [comment]
The question really was, why does the API give very much different response/code than ChatGPT, when it's suppose to be the same model? But I see this questin is also asked on the OpenAi forum. The ChatGPT model may be very different model, than the one accessible via API, and/or the temperature may affect the response.
I't would still be nice to try adjusting the temperature, to see how it affects to the response. Maybe even set the temperature with each prompt on the fly or add new command for it, /temperature 0.7

**Comment by paul-gauthier** [comment]
I'm reluctant to add new config/settings options without a good reason. There are already quite a lot of knobs and settings.

But yes, there are many ways in which the output of the web chatgpt should be expected to differ from the raw openai api. But the responses GPT sends in aider chats will be much, much different than the chatgpt web ui because aider has a very different system prompt.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to re-open or file a new issue any time.

**Comment by cipherCOM** [comment]
One example of temperatures above 0.0 as a recommendation by the creators of the model: https://huggingface.co/deepseek-ai/DeepSeek-R1#deepseek-r1-distill-models-1

**Comment by paul-gauthier** [comment]
You can now specify a float for the `use_temperature` model setting, like this:

```yaml
- name: fireworks_ai/accounts/fireworks/models/deepseek-r1
  edit_format: diff
  weak_model_name: fireworks_ai/accounts/fireworks/models/deepseek-v3
  use_repo_map: true
  use_temperature: false
  streaming: true
  editor_model_name: fireworks_ai/accounts/fireworks/models/deepseek-v3
  editor_edit_format: editor-diff
  remove_reasoning: think
  extra_params:
      max_tokens: 160000
  use_temperature: 0.5
```

The change is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade --upgrade-strategy only-if-needed git+https://github.com/Aider-AI/aider.git
```

If you have a chance to try it, let me know if it works better for you.
