### ISSUE TITLE
--no-gui command

### ISSUE THREAD

**Issue by shipurjan** [Aider-AI/aider#2152]
### Issue

I'm using `gui: true` in my repository's aider config, because I would like it to be the default

```yml
cache-prompts: true
stream: false
gui: true
show-diffs: true
show-model-warnings: false
chat-language: en
subtree-only: true
```

But sometimes I would want to overwrite this setting and run Aider in CLI, but currently there's no `--no-gui` option

### Version and model info

```
Aider v0.60.1
Main model: claude-3-5-sonnet-20241022 with diff edit format, prompt cache, infinite output
Weak model: claude-3-haiku-20240307
Git repo: .git with 3,514 files
Warning: For large repos, consider using --subtree-only and .aiderignore
See: https://aider.chat/docs/faq.html#can-i-use-aider-in-a-large-mono-repo
Repo-map: using 1024 tokens, files refresh
```
