### ISSUE TITLE
Line editor doesn't respond to `Ctrl + Z`

### ISSUE THREAD

**Issue by mcevoypeter** [Aider-AI/aider#2528]
### Issue

Pressing `Ctrl + Z` in the line editor does not suspend Aider as I'd expect for any normall shell job. The only way I'm able to suspend Aider is by manually sending `SIGTSTP` via `kill`. Attached is a screen recording of what I'm describing. Note the issue is reproducible outside of Tmux. It's also reproducible with Vim mode disabled.

https://github.com/user-attachments/assets/cb6b2ad9-98f5-4b43-b924-1b00239be141

Aider configuration file (at `~/.aider.conf.yml`):

```yaml
# https://aider.chat/docs/config/aider_conf.html

auto-commits: false
gitignore: false
vim: true

anthropic-api-key: REDACTED
```

### Version and model info

Aider: 0.66.0
Zsh: 5.9 (x86_64-apple-darwin23.0)
Tmux: stable 3.5a
Alacritty: 0.13.2 (bb8ea18)
macOS: 14.5 (23F79)
