### ISSUE TITLE
Read-only chat modes documentation is ambiguous

### ISSUE THREAD

**Issue by PaulWaldo** [Aider-AI/aider#2848]
### Issue

The docs at [In-chat commands | aider](https://aider.chat/docs/usage/commands.html) say the folowing:l

* `/architect`	Enter architect mode to discuss high-level design and architecture. If no prompt provided, switches to architect mode.
* `/ask` Ask questions about the code base without editing any files. If no prompt provided, switches to ask mode.

Based on these descriptions, it is difficult to tell which mode to use.  
* How do the two differ?  
* Isn't discussing architecture the same thing as asking things about the code base?  
* What are the advantages and disadvantages of each?

### Version and model info

```
Aider v0.71.1
Model: openai/hf:meta-llama/Llama-3.1-405B-Instruct with whole edit format
Git repo: .git with 32 files
Repo-map: using 512 tokens, auto refresh
Added project_docs/vision/project_vision.md to the chat (read-only).
Added project_docs/requirements/core_requirements.md to the chat (read-only).
Added ../../third-party/software-dev-prompt-library/prompts/architecture/assistant-specific/aider/tech-stack-prompt.md to the 
chat (read-only).
Added 
../../third-party/software-dev-prompt-library/prompts/requirements/assistant-specific/aider/initial-project-requirements-manag
ement-prompt.md to the chat (read-only).
Added go.mod to the chat (read-only).
Restored previous conversation history.
Config File (/Users/paul/src/personal/glimmer/.aider.conf.yml):
  model:             openai/hf:meta-llama/Llama-3.1-405B-Instruct
  openai-api-base:   https://glhf.chat/api/openai/v1
  map-tokens:        512
  attribute-committer:True
  attribute-commit-message-author:True
  attribute-author:  True
Defaults:
  --set-env:         []
  --api-key:         []
  --model-settings-file:.aider.model.settings.yml
  --model-metadata-file:.aider.model.metadata.json
  --cache-keepalive-pings:0
  --map-refresh:     auto
  --map-multiplier-no-files:2
  --input-history-file:/Users/paul/src/personal/glimmer/.aider.input.history
  --chat-history-file:/Users/paul/src/personal/glimmer/.aider.chat.history.md
  --user-input-color:#00cc00
  --tool-error-color:#FF2222
  --tool-warning-color:#FFA500
  --assistant-output-color:#0088ff
  --code-theme:      default
  --aiderignore:     /Users/paul/src/personal/glimmer/.aiderignore
  --lint-cmd:        []
  --test-cmd:        []
  --voice-format:    wav
  --voice-language:  en
  --encoding:        utf-8
  --env-file:        /Users/paul/src/personal/glimmer/.env

Option settings:
  - aiderignore: /Users/paul/src/personal/glimmer/.aiderignore
  - alias: None
  - analytics: None
  - analytics_disable: False
  - analytics_log: None
  - anthropic_api_key: None
  - api_key: []
  - apply: None
  - apply_clipboard_edits: False
  - assistant_output_color: #0088ff
  - attribute_author: True
  - attribute_commit_message_author: True
  - attribute_commit_message_committer: False
  - attribute_committer: True
  - auto_commits: True
  - auto_lint: True
  - auto_test: False
  - cache_keepalive_pings: 0
  - cache_prompts: False
  - chat_history_file: /Users/paul/src/personal/glimmer/.aider.chat.history.md
  - chat_language: None
  - check_update: True
  - code_theme: default
  - commit: False
  - commit_prompt: None
  - completion_menu_bg_color: None
  - completion_menu_color: None
  - completion_menu_current_bg_color: None
  - completion_menu_current_color: None
  - config: None
  - copy_paste: False
  - dark_mode: False
  - detect_urls: True
  - dirty_commits: True
  - dry_run: False
  - edit_format: None
  - editor: None
  - editor_edit_format: None
  - editor_model: None
  - encoding: utf-8
  - env_file: /Users/paul/src/personal/glimmer/.env
  - exit: False
  - fancy_input: True
  - file: None
  - files: []
  - git: True
  - gitignore: True
  - gui: False
  - input_history_file: /Users/paul/src/personal/glimmer/.aider.input.history
  - install_main_branch: False
  - just_check_update: False
  - light_mode: False
  - lint: False
  - lint_cmd: []
  - list_models: None
  - llm_history_file: None
  - load: None
  - map_multiplier_no_files: 2
  - map_refresh: auto
  - map_tokens: 512
  - max_chat_history_tokens: None
  - message: None
  - message_file: None
  - model: openai/hf:meta-llama/Llama-3.1-405B-Instruct
  - model_metadata_file: .aider.model.metadata.json
  - model_settings_file: .aider.model.settings.yml
  - multiline: False
  - openai_api_base: https://glhf.chat/api/openai/v1
  - openai_api_deployment_id: None
  - openai_api_key: None
  - openai_api_type: None
  - openai_api_version: None
  - openai_organization_id: None
  - pretty: True
  - read: None
  - restore_chat_history: False
  - set_env: []
  - show_diffs: False
  - show_model_warnings: True
  - show_prompts: False
  - show_release_notes: None
  - show_repo_map: False
  - skip_sanity_check_repo: False
  - stream: True
  - subtree_only: False
  - suggest_shell_commands: True
  - test: False
  - test_cmd: []
  - timeout: None
  - tool_error_color: #FF2222
  - tool_output_color: None
  - tool_warning_color: #FFA500
  - upgrade: False
  - user_input_color: #00cc00
  - verbose: False
  - verify_ssl: True
  - vim: False
  - voice_format: wav
  - voice_input_device: None
  - voice_language: en
  - watch_files: False
  - weak_model: None
  - yes_always: None
```
