### ISSUE TITLE
Can't get aider to work in powershell

### ISSUE THREAD

**Issue by harleypig** [Aider-AI/aider#2870]
### Issue

I'm unsure if this is a bug, if I'm doing something wonky, or if I'm doing both. I'm using Windows 11, with both Cygwin bash and Powershell. I installed it via Powershell according to the instructions [here](https://aider.chat/docs/install.html#windows).

I can't figure out what I'm doing wrong. Any help would be appreciated.

On Cygwin bash, aider works fine.

```bash
$ echo $OPENAI_API_KEY ; aider --message 'ping'
sk-proj-****7cA
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Aider v0.70.0
Main model: gpt-4o-2024-08-06 with diff edit format
Weak model: gpt-4o-mini
Git repo: .git with 433 files
Repo-map: using 2048 tokens, auto refresh

Pong! How can I assist you today?


Tokens: 6.8k sent, 10 received. Cost: $0.02 message, $0.02 session.
```

Powershell won't work even with the api key set on the command line.

```powershell
PS C:\Users\harleypig\cygwin\projects\dotfiles> $OPENAI_API_KEY ; $env:OPENAI_API_KEY ; aider --message 'ping'
sk-proj-****7cA

sk-proj-****7cA

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Aider v0.70.0
Main model: gpt-4o-2024-08-06 with diff edit format
Weak model: gpt-4o-mini
Git repo: .git with 433 files
Repo-map: using 2048 tokens, auto refresh

litellm.APIError: APIError: OpenAIException - Connection error.
Retrying in 0.2 seconds...
litellm.APIError: APIError: OpenAIException - Connection error.
Retrying in 0.5 seconds...


^C again to exit


PS C:\Users\harleypig\cygwin\projects\dotfiles> aider --openai-api-key="$OPENAI_API_KEY" --message 'ping'
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Aider v0.70.0
Main model: gpt-4o-2024-08-06 with diff edit format
Weak model: gpt-4o-mini
Git repo: .git with 433 files
Repo-map: using 2048 tokens, auto refresh

litellm.APIError: APIError: OpenAIException - Connection error.
Retrying in 0.2 seconds...
litellm.APIError: APIError: OpenAIException - Connection error.
Retrying in 0.5 seconds...


^C again to exit
```

I copied the output of `/settings` from both environments. In the interest of space, I'll paste the bash output and then provide a unified diff between the two. As you'll see, the only differences are the `AIDER_EDITOR` environment variable and the `editor:` setting (affected by the presence or lack of the environment variable).

```
Aider v0.70.0
Main model: gpt-4o-2024-08-06 with diff edit format
Weak model: gpt-4o-mini
Git repo: .git with 433 files
Repo-map: using 2048 tokens, auto refresh

Environment Variables:
  AIDER_MAX_CHAT_HISTORY_TOKENS:2048
  AIDER_MAP_TOKENS:  2048
  AIDER_DARK_MODE:   true
  AIDER_GITIGNORE:   false
  AIDER_WATCH_FILES: true
  AIDER_VIM:         true

Defaults:
  --set-env:         []
  --api-key:         []
  --model-settings-file:.aider.model.settings.yml
  --model-metadata-file:.aider.model.metadata.json
  --cache-keepalive-pings:0
  --map-refresh:     auto
  --map-multiplier-no-files:2
  --input-history-file:C:\Users\harleypig\cygwin\projects\dotfiles\.aider.input.history
  --chat-history-file:C:\Users\harleypig\cygwin\projects\dotfiles\.aider.chat.history.md
  --user-input-color:#00cc00
  --tool-error-color:#FF2222
  --tool-warning-color:#FFA500
  --assistant-output-color:#0088ff
  --code-theme:      default
  --aiderignore:     C:\Users\harleypig\cygwin\projects\dotfiles\.aiderignore
  --lint-cmd:        []
  --test-cmd:        []
  --voice-format:    wav
  --voice-language:  en
  --encoding:        utf-8
  --env-file:        C:\Users\harleypig\cygwin\projects\dotfiles\.env

Option settings:
  - aiderignore: C:\Users\harleypig\cygwin\projects\dotfiles\.aiderignore
  - alias: None
  - analytics: None
  - analytics_disable: False
  - analytics_log: None
  - anthropic_api_key: None
  - api_key: []
  - apply: None
  - apply_clipboard_edits: False
  - assistant_output_color: #00FFFF
  - attribute_author: True
  - attribute_commit_message_author: False
  - attribute_commit_message_committer: False
  - attribute_committer: True
  - auto_commits: True
  - auto_lint: True
  - auto_test: False
  - cache_keepalive_pings: 0
  - cache_prompts: False
  - chat_history_file: C:\Users\harleypig\cygwin\projects\dotfiles\.aider.chat.history.md
  - chat_language: None
  - check_update: True
  - code_theme: monokai
  - commit: False
  - commit_prompt: None
  - completion_menu_bg_color: None
  - completion_menu_color: None
  - completion_menu_current_bg_color: None
  - completion_menu_current_color: None
  - config: None
  - copy_paste: False
  - dark_mode: True
  - detect_urls: True
  - dirty_commits: True
  - dry_run: False
  - edit_format: None
  - editor: None
  - editor_edit_format: None
  - editor_model: None
  - encoding: utf-8
  - env_file: C:\Users\harleypig\cygwin\projects\dotfiles\.env
  - exit: False
  - fancy_input: True
  - file: None
  - files: []
  - git: True
  - gitignore: False
  - gui: False
  - input_history_file: C:\Users\harleypig\cygwin\projects\dotfiles\.aider.input.history
  - install_main_branch: False
  - just_check_update: False
  - light_mode: False
  - lint: False
  - lint_cmd: []
  - list_models: None
  - llm_history_file: None
  - load: None
  - map_multiplier_no_files: 2
  - map_refresh: auto
  - map_tokens: 2048
  - max_chat_history_tokens: 2048
  - message: None
  - message_file: None
  - model: gpt-4o-2024-08-06
  - model_metadata_file: .aider.model.metadata.json
  - model_settings_file: .aider.model.settings.yml
  - multiline: False
  - openai_api_base: None
  - openai_api_deployment_id: None
  - openai_api_key: None
  - openai_api_type: None
  - openai_api_version: None
  - openai_organization_id: None
  - pretty: True
  - read: None
  - restore_chat_history: False
  - set_env: []
  - show_diffs: False
  - show_model_warnings: True
  - show_prompts: False
  - show_release_notes: None
  - show_repo_map: False
  - skip_sanity_check_repo: False
  - stream: True
  - subtree_only: False
  - suggest_shell_commands: True
  - test: False
  - test_cmd: []
  - timeout: None
  - tool_error_color: #FF3333
  - tool_output_color: None
  - tool_warning_color: #FFFF00
  - upgrade: False
  - user_input_color: #32FF32
  - verbose: False
  - verify_ssl: True
  - vim: True
  - voice_format: wav
  - voice_input_device: None
  - voice_language: en
  - watch_files: True
  - weak_model: None
  - yes_always: None
 ```

And the diff between the two files.

```diff
$ diff -u work/{ps,bash}-settings.txt 
--- work/ps-settings.txt        2025-01-14 20:48:11.789261600 -0700
+++ work/bash-settings.txt      2025-01-14 20:34:21.336342600 -0700
@@ -11,7 +11,6 @@
   AIDER_GITIGNORE:   false
   AIDER_WATCH_FILES: true
   AIDER_VIM:         true
-  AIDER_EDITOR:      code --wait

 Defaults:
   --set-env:         []
@@ -73,7 +72,7 @@
   - dirty_commits: True
   - dry_run: False
   - edit_format: None
-  - editor: code --wait
+  - editor: None
   - editor_edit_format: None
   - editor_model: None
   - encoding: utf-8
 ```

### Version and model info

Aider v0.70.0
Main model: gpt-4o-2024-08-06 with diff edit format
Weak model: gpt-4o-mini
Git repo: .git with 433 files
Repo-map: using 2048 tokens, auto refresh
