### ISSUE TITLE
Using openrouter r1 as architect, sonnet as editor and deepseek-chat as weak-model

### ISSUE THREAD

**Issue by GratefulDave** [Aider-AI/aider#3095]
### Issue

I am trying to use:
- Architect: r1
- Editor: claude-3.5-sonnet
- Weak Model: deepseek-chat

When I run `aider`, the output is:
```
Found OPENROUTER_API_KEY so using openrouter/anthropic/claude-3.5-sonnet since no --model was specified.
Aider v0.73.0
Model: openrouter/anthropic/claude-3.5-sonnet with whole edit format, infinite output
Git repo: .git with 166 files
Repo-map: using 4092 tokens, auto refresh
```
What I expect is:

<img width="297" alt="Image" src="https://github.com/user-attachments/assets/d6679ae3-e6a4-4408-a17c-3252d83f8c5f" />

If I run `aider --model r1`:
```
aider --model r1
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Warning: deepseek/deepseek-reasoner expects these environment variables
- DEEPSEEK_API_KEY: Not set
Warning: deepseek/deepseek-chat expects these environment variables
- DEEPSEEK_API_KEY: Not set
Warning: deepseek/deepseek-chat expects these environment variables
- DEEPSEEK_API_KEY: Not set
You can skip this check with --no-show-model-warnings

https://aider.chat/docs/llms/warnings.html
Open documentation url for more info? (Y)es/(N)o/(D)on't ask again [Yes]: N                                                                        

Aider v0.73.0
Main model: deepseek/deepseek-reasoner with diff edit format, prompt cache, infinite output
Weak model: deepseek/deepseek-chat
Git repo: .git with 166 files
Repo-map: using 4092 tokens, auto refresh
```
Right now I can't even get a new deepseek api token because I get a 503 every time I try to login to the api.

Here are my settings:

.aider.config.yml
```
api-key:
  openrouter: {api_key}
architect: true
model: openrouter/deepseek/deepseek-reasoner
editor-model: openrouter/anthropic/claude-3.5-sonnet
weak-model: openrouter/deepseek/deepseek-chat
multiline: true
watch-files: true
map-tokens: 4092
map-refresh: auto
dark-mode: true
pretty: true
cache-prompts: true
```
.aider.model.settings.yml
```
- name: openrouter/anthropic/claude-3.5-sonnet
  extra_params:
    extra_body:
      provider:
        # Only use these providers, in this order
        order: ["Anthropic"]
        # Don't fall back to other providers
        allow_fallbacks: false
        # Skip providers that may train on inputs
        data_collection: "deny"
        # Only use providers supporting all parameters
        require_parameters: true

- name: openrouter/deepseek/deepseek-r1:free
  extra_params:
    extra_body:
      provider:
        # Only use these providers, in this order
        order: ["Chute"]
        # Don't fall back to other providers
        allow_fallbacks: false
        # Skip providers that may train on inputs
        data_collection: "deny"
        # Only use providers supporting all parameters
        require_parameters: true

- name: openrouter/deepseek/deepseek-chat
  extra_params:
    extra_body:
      provider:
        # Only use these providers, in this order
        order: ["DeepSeek", "Nebia", "Fireworks"]
        # Don't fall back to other providers
        allow_fallbacks: false
        # Skip providers that may train on inputs
        data_collection:
        # Only use providers supporting all parameters
        require_parameters: true
```

### Version and model info

Aider v0.73.0
Model: As above
Repo-Map: 4192
