### ISSUE TITLE
Could you add Glama.ai as provider or recommend way to use it? To get ability use o3-mini high without Tier3+

### ISSUE THREAD

**Issue by it-sha** [Aider-AI/aider#3105]
### Issue

Probably, this is the only provider that allows you to work with o3-mini-high for users on the regular tier.
Neither OpenAI, OpenRouter, nor Azure provides such opportunities now.

### Version and model info

Aider: 0.73.0

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. This doc may be helpful:

https://aider.chat/docs/llms/openai-compat.html

**Comment by cosmojg** [comment]
@it-sha Create the following file (`.aider.model.settings.yml`) in either your code repository or your home directory:

```yaml
- name: openai/o3-mini-high
  edit_format: diff
  weak_model_name: openai/gpt-4o
  use_repo_map: true
  use_system_prompt: false
  use_temperature: false
  editor_model_name: openai/gpt-4o-mini
  editor_edit_format: editor-diff
```

Then run: `OPENAI_API_BASE="https://glama.ai/api/gateway/openai/v1/" OPENAI_API_KEY=$GLAMA_API_KEY aider --model openai/o3-mini-high`
