### ISSUE TITLE
How to use multiple, separate open-ai compatible API endpoints at the same time

### ISSUE THREAD

**Issue by jameslamine** [Aider-AI/aider#3125]
### Issue

I have access to multiple openai-compatible endpoints. The each use a different URL and API key. I'd like to use a mix of these, for example use one API endpoint for weak-model, one for architect model, and one for editor-model.

Alternatively we could use the same URL but separate API keys for different models.

How can I do this? Right now it seems like I can only configure a single `AIDER_OPENAI_API_BASE`

**Comment by PurpleSwords** [comment]
I have the same problem

**Comment by AuroraPixel** [comment]
One API can solve your problems.

**Comment by PurpleSwords** [comment]
> One API can solve your problems.

Yes, this is my current solution. But docker has a requirement for a minimum version of windows, and even in the case where I force it to install it, I can only use the hyper-v method, which creates another problem, my VMware VMs won't run, and they can't run at the same time with lower versions of windows. All in all a lot of problems and would prefer to have a solution from the source, otherwise I would need to upgrade the system which I'm afraid would create more additional problems.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

I think you can achieve this with a `.aider.model.settings.yml` file:

```
- name: openai/one-model
  extra_params:
    api_key: <key>
    api_base: https://one-models-api.com/

- name: openai/second-model
  extra_params:
    api_key: <key>
    api_base: https://second-models-api.com/
```

You will need to provide all the other model settings for each model.


See also: https://github.com/Aider-AI/aider/issues/2987
