### ISSUE TITLE
Custom colors not applied

### ISSUE THREAD

**Issue by FabianHofmann** [Aider-AI/aider#3163]
### Issue

Specifying the font colors in the `~/.aider.conf.yml` does not lead to any changes in the displayed text. I use the following settings

```yaml
## Set the color for user input (default: #00cc00)
user-input-color: #c9d2a3

## Set the color for tool output (default: None)
tool-output-color: #c9d2a3

## Set the color for tool error messages (default: #FF2222)
tool-error-color: #ff3333

## Set the color for tool warning messages (default: #FFA500)
tool-warning-color: #FFA500

## Set the color for assistant output (default: #0088ff)
assistant-output-color: #4b7498
``` 

which do not have any effect. I would have expected the text of the input and output in the chat to be customizable by this. Am I wrong here?

### Version and model info

Aider v0.73.0
Main model: deepseek/deepseek-reasoner with architect edit format, prompt cache, infinite output
Editor model: deepseek/deepseek-chat with editor-diff edit format
Weak model: deepseek/deepseek-chat
Git repo: .git with 365 files
Repo-map: using 4096 tokens, auto refresh
Multiline mode: Enabled. Enter inserts newline, Alt-Enter submits text
