### ISSUE TITLE
lint-cmd configuation needs more examples

### ISSUE THREAD

**Issue by chr15m** [Aider-AI/aider#3164]
### Issue

Hi, thank you for creating such an amazing tool and making it open source. 🙏

I am trying to configure a custom linter for a fairly niche language. Here is what I am trying:

```
auto-lint: true
lint-cmd:
 - clojurescript: clj-kondo --lint
 - clojure: clj-kondo --lint
 - cljs: clj-kondo --lint
```

Which results in the following error:

```
/bin/sh: line 1: {cljs:: command not found

# Fix any errors below, if possible.

## Running: {'cljs': 'clj-kondo --lint'} style.css

/bin/sh: line 1: {cljs:: command not found

## See relevant line below marked with █.

style.css:
```

It seems like it's trying to run the entire last YAML block converted to JSON as the command. How can I specify that I want files with extension `*.cljs` to be run with a particular command, and no other files run with that command?

Thank you very much.

### Version and model info

aider 0.73.0
