### ISSUE TITLE
Configuring LLMLite proxy

### ISSUE THREAD

**Issue by shaharkedar** [Aider-AI/aider#3218]
### Issue

I'm trying to configure a private LLMLite proxy instance as the openapi base URL for aider and it doesn't seem to be working. Aider keeps complaining about an incorrect key (which is a fake key I admit, but it shouldn't be necessary when using the proxy). Here's the config file I'm using:

```
## Use claude-3-5-sonnet-20241022 model for the main chat
sonnet: true


########################
# API Keys and settings:

## Specify the OpenAI API key
openai-api-key: xxx

## Specify the Anthropic API key
anthropic-api-key: xxx

## Specify the api base url (this URL is a fake one. In my setup I use a working URL)
openai-api-base: https://llmliteproxy.privatedomain.com

```

And this is the error I'm getting:

```
litellm.AuthenticationError: AnthropicException - b'{"type":"error","error":{"type":"authentication_error","message":"invalid x-api-key"}}'
The API provider is not able to authenticate you. Check your API key.
```

### Version and model info

Aider 0.74.2

**Comment by bradsjm** [comment]
Aider uses litellm so it has native support for litellm proxy, so you would do this in your config file. Just use the special prefix "litellm_proxy/" then the model name as you have it in your proxy. You still need a valid key, the default for LiteLLM proxy is "sk-1234" unless you changed it or have created virtual keys.

You could also just set environment variables natively in your shell but I like to keep them in the config file.

```
model: litellm_proxy/gemini-2.0-flash-thinking-exp
editor-model: litellm_proxy/gemini-2.0-pro-exp
weak-model: litellm_proxy/gemini-2.0-flash-exp

env:
  - LITELLM_PROXY_API_BASE=http://X.X.X.X:4000
  - LITELLM_PROXY_API_KEY=sk-1234
```

**Comment by BenSmith** [comment]
This worked great for me, thanks @bradsjm

**Comment by FuturMix** [comment]
@psychomelet — Yes, you can set per-model API bases using `.aider.model.settings.yml`:

```yaml
- name: openai/claude-sonnet-4-6
  extra_params:
    api_key: sk-xxx
    api_base: https://provider-a.example.com/v1

- name: openai/gpt-5.4
  extra_params:
    api_key: sk-yyy
    api_base: https://provider-b.example.com/v1

- name: openai/gemini-2.5-flash
  extra_params:
    api_key: sk-zzz
    api_base: https://provider-c.example.com/v1
```

Then launch with:
```bash
aider --model openai/claude-sonnet-4-6 \
      --weak-model openai/gemini-2.5-flash \
      --editor-model openai/gpt-5.4
```

Each model resolves its own `api_base` and `api_key` independently. You'll also want to set `edit_format`, `use_repo_map`, etc. per model — see [aider's model settings docs](https://aider.chat/docs/config/adv-model-settings.html).

Alternatively, if all models you need are available from a single OpenAI-compatible aggregator (OpenRouter, FuturMix, etc.), you can skip per-model routing entirely — one `OPENAI_API_BASE` + one key covers everything:

```bash
export OPENAI_API_BASE=https://aggregator.example.com/v1
export OPENAI_API_KEY=sk-xxx
aider --model openai/claude-sonnet-4-6 --weak-model openai/gemini-2.5-flash
```

The tradeoff is that per-model settings give you maximum control (different keys, different proxies), while a single aggregator endpoint is simpler to manage.

---
*Disclosure: we run [FuturMix](https://futurmix.ai), an OpenAI-compatible API with 20+ models.*
