### ISSUE TITLE
Can we merge all configuration files into one?

### ISSUE THREAD

**Issue by TheBestPessimist** [Aider-AI/aider#3263]
### Issue

Right now i use 2 separate configuration files: `.aider.conf.yml` and `.aider.model.settings.yml`. Is there a possibility to move all the configuration into `aider.conf.yml`?

**Comment by TheBestPessimist** [comment]
For that matter, could i also add the costs to the same file, instead of having to create a third file which is `json` this time and not `yaml`?

```yaml
- name: some-model
  edit_format: diff 
  editor_edit_format: editor-diff
  remove_reasoning: think
  extra_params:
    input_cost_per_token: 0.00000014   <------
    output_cost_per_token: 0.00000028 <---------
```
