### ISSUE TITLE
Feature Suggestion: User Defined Commands (as plugins)

### ISSUE THREAD

**Issue by whitmo** [Aider-AI/aider#3305]
_related to #1814_

Biffed calling `pytest` without  `/run uv run pytest` for the nth time and decided investigated how adding commands might look.   Thought I would share and invite feedback.

### Why
- Support creating personalized workflows inside Aider 
  - _i.e load up a specific set of commands for a yourself, a specific language, a repo, a project, etc_
- Support creating a specific kind of context needed for aider to successful make progress on a specific task
   - _i.e. use Aider to write a command to check all the imports in a package so Aider can fix all the broken imports_. 
- Self serve and easy integration to lower friction 

### What/How
This [reference implementation](https://github.com/whitmo/aider/pull/1) provides a user command registry and dispatcher loaded from standard aider config files or arbitrary yaml files.  Support shell aliases, python based plugins, and python based `overrides` which can wrap or replace existing commands.  User command dispatch supersedes standard command dispatch.  

From the PR,  an explanative example. Given: `some-cmd-file.yaml` contains

```yaml
commands:
  date:
    type: shell
    definition: "date"
    description: "Show current date/time"
    
  greet:
    type: plugin
    definition: mypackage.greetings.say_hello
    description: "Greet the user"
```

Add the commands from aider:  
```
> /cmd add some-cmd-file.yaml
Added commands: greet, date
> /greet
"HELLO"
/date 
Tue Feb 18 17:35:07 PST 2025
```

The flag `--cmd-file` (usable multiple times) will also allow aider to load user commands at script execution time.   

ex: `$ aider --cmd-file=some-cmd-file.yaml`

See [reference implementation](https://github.com/whitmo/aider/pull/1) for more examples.

### Caveats / Critiques
- All this can be done w/ `/run` in one fashion or another.  It is a bit like syntactic sugar.
- Defining a `commands` key in the existing configuration files required defining a `--commands` flag in the argparser.   This feels like a smell in my implementation.
- I did decent manual testing for shell and python plugins, not much testing for overrides. YMMV. 
- While it is nice to be able to override a native command, there are no guards to speak of atm.

**Comment by harleypig** [comment]
I think this is similar, but not identical, to [#99](https://github.com/Aider-AI/aider/issues/99).

**Comment by whitmo** [comment]
@harleypig I think you could implement the functions described in #99 using the reference implementation.

**Comment by harleypig** [comment]
I like this, especially the override option, and I hope it gets merged.

However, I don't see a way to do something like the following (where `mkissue` is my custom command), unless I missed a way to call other functions.

```
> /mkissue gitbug Go through the loaded files, looking for 'XXX', 'TODO', and 'FIXME' comments and create a separate and well-formed issue for each
```
(or `gh` or whatever)

**Comment by whitmo** [comment]
@harleypig  yeah, this implementation doesn't do any arg parsing and dispatching outside of a plugin to to create a more "command line" like behavior.    You can of course do anything inside the plugin, like matching an issue poster, or sending a prompt to do some intermediate work.

And one can parse the arguments sent in however, but there is no generalized behavior to stack or pipe commands.

Your example makes me think about having simple configuration for plugins. One is like to have steady preference to how one defines issues in the code, as well as where one is posting tracker issues. 

```yaml
commands:
  mkissue:
    type: plugin
   definition: path.to.mkissue_plugin
    plugin_config:
       issue_prompt: | 
         Go through the loaded files, looking for 'XXX', 'TODO', and 'FIXME' comments 
         and create a separate and well-formed issue for each

       issue_handler:  gitbug
   
```
