### ISSUE TITLE
Is it possible to create multiple model configurations for the same model?

### ISSUE THREAD

**Issue by V4G4X** [Aider-AI/aider#3365]
### Issue

Basically, I want to be able to define two aliases:
```
 - sonnet
 - sonnet_think
```

Where `sonnet_think` is just Sonnet 3.7 with thinking enabled.

I tried adding this in my settings.yml:
```
- name: sonnet_think
  edit_format: diff
  weak_model_name: anthropic/claude-3-5-haiku-20241022
  use_repo_map: true
  examples_as_sys_msg: true
  use_temperature: false
  extra_params:
    extra_headers:
      anthropic-beta: prompt-caching-2024-07-31,pdfs-2024-09-25,output-128k-2025-02-19
    max_tokens: 64000
    thinking:
      type: enabled
      budget_tokens: 32000 # Adjust this number
  cache_control: true
  editor_model_name: anthropic/claude-3-7-sonnet-20250219
  editor_edit_format: editor-diff
```

But obviously, it couldn't resolve this to the proper Anthropic's API.

### Version and model info

aider 0.75.2.dev3+gb6e46d61
