### ISSUE TITLE
Glob for read/file config in yaml

### ISSUE THREAD

**Issue by mneuhaus** [Aider-AI/aider#3366]
Currently i can only specify specific files in the yaml to read or add on start, but it would be really useful to enable glob to include whole folders like for example a docs folder: 

```yaml
file:
    - docs/*

read:
    - docs/*
```
