### ISSUE TITLE
Set reasoning behaviour in Claude 3.7 when using bedrock

### ISSUE THREAD

**Issue by dayglo** [Aider-AI/aider#3386]
### Issue

hi,

I use claude through bedrock using `--model bedrock/anthropic.claude-3-5-sonnet-20241022-v2:0`

Is there a way i can set up the reasoning behaviour in aider? This article seems to suggest bedrock supports setting it...

https://community.aws/content/2tX54cKIma0hagyddSKMeYwT6sm/how-to-use-reasoning-with-claude-3-7-sonnet-on-amazon-bedrock-javascript-edition

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/bedrock-runtime/command/ConverseCommand/

### Version and model info

Aider 0.74.3

**Comment by dayglo** [comment]
Ah. I see that you need to wait for litellm to add support before you can use it. 

https://docs.litellm.ai/docs/providers/bedrock#supported-aws-bedrock-models

**Comment by krrishdholakia** [comment]
Hey @dayglo the ticket you linked is the anthropic api support.

Bedrock ticket is here - https://github.com/BerriAI/litellm/issues/8777

Working on adding support now - https://github.com/BerriAI/litellm/pull/8843

**Comment by krrishdholakia** [comment]
> litellm.BadRequestError: BedrockException - b'{"message":"Invocation of model ID anthropic.claude-3-7-sonnet-20250219-v1:0 with on-demand throughput isn\xe2\x80\x99t supported. Retry your request with


this indicates claude-3-7 needs to be called via a cross-region inferencing endpoint - `us.anthropic.claude-3-7-sonnet-20250219-v1:0`

**Comment by jake-klingler** [comment]
> this indicates claude-3-7 needs to be called via a cross-region inferencing endpoint - `us.anthropic.claude-3-7-sonnet-20250219-v1:0`

Yep, that fixed it, thanks for the tip!

**Comment by krrishdholakia** [comment]
Will improve our error message here

**Comment by strayer** [comment]
So far it seems doing this in your `~/.aider.model.settings.yml` enabled the thinking behaviour for Sonnet 3.7 on Bedrock:

```yaml
- name: bedrock/us.anthropic.claude-3-7-sonnet-20250219-v1:0
  edit_format: diff
  use_temperature: false # not compatible with thinking mode
  extra_params:
    max_tokens: 64000 # must be greater than budget_tokens
    thinking:
      type: enabled
      budget_tokens: 32000 # Adjust this number
```
