### ISSUE TITLE
How to make DeepSeek thinking process more concise and short ? thinking-tokens is ignored

### ISSUE THREAD

**Issue by GeorgeFlorian** [Aider-AI/aider#3546]
### Issue

I am running using a simple `aider` command as I have created 2 global config files:
```yml
# ~/.aider.conf.yml
model: openrouter/deepseek/deepseek-r1
architect: true
editor-model: openrouter/anthropic/claude-3.5-sonnet
auto-accept-architect: false
auto-commits: false

cache-prompts: true

dark-mode: true

# lint: true

## Set the thinking token budget for models that support it (default: not set)
thinking-tokens: 100
```

```yml
#~/.aider.model.setting.yml
- name: openrouter/deepseek/deepseek-r1
  extra_params:
    top_p: 0.95
  use_temperature: 0.6
```

I also created `~/ai-instructions.md` that I include with the /read command once I open aider:
```md
# Tone and style

You should be concise, direct, and to the point.

Remember that your output will be displayed on a command line interface.

IMPORTANT: You should minimize output tokens as much as possible while maintaining helpfulness, quality, and accuracy.

IMPORTANT: You should NOT answer with unnecessary preamble or postamble (such as summarizing your action), unless the user asks you to.

IMPORTANT: You MUST answer concisely with fewer than 4 lines (not including tool use or code generation) unless user asks for detail. Answer the user's question directly. Avoid introductions, conclusions, and explanations. You MUST avoid text before/after your response, such as "The answer is <answer>.", "Here is the content of the file..." or "Based on the information provided, the answer is..." or "Here is what I will do next...". Omit all filler phrases.
```

All of that and the thinking process is still huge:

![Image](https://github.com/user-attachments/assets/5f111987-2eb5-4672-af75-a7b700a9acfc)

![Image](https://github.com/user-attachments/assets/53818d0a-dd14-4f09-92ca-dcf0932c856e)

### Version and model info

Aider v0.77.0
Main model: openrouter/deepseek/deepseek-r1 with architect edit format, 0.1k think tokens, prompt cache, infinite output
Editor model: openrouter/anthropic/claude-3.5-sonnet with editor-diff edit format
Weak model: openrouter/deepseek/deepseek-chat
Git repo: .git with 24 files
Repo-map: using 4096 tokens, files refresh
