### ISSUE TITLE
Ollama keeps unloading my models each request

### ISSUE THREAD

**Issue by lubek-dc** [Aider-AI/aider#3594]
### Issue

![Image](https://github.com/user-attachments/assets/7917b3d7-9800-40a5-b4fb-ee69c30a271a)

everything is loaded until i put in a prompt into the aider then it starts to load each gpu up again A

![Image](https://github.com/user-attachments/assets/7b4ca6f2-6c86-4ee7-b066-e1ec48f03c6a)

![Image](https://github.com/user-attachments/assets/922b4e46-d138-4da5-83b7-dfe6ff6b5fa9)

also keep in mind that i am the only user of this and i also use the openweb-ui and when i use it on there it works fine it dosent unload it it just works.

### Version and model info

Aider:  0.77.1
Model: Ollama/Deepseek-r1:70b

**Comment by k0zakinio** [comment]
Also experiencing the same.  Did you manage to fix it?

**Comment by k0zakinio** [comment]
I think I understand the issue, not sure how to resolve it.  Aider's context length is changing with every request which triggers the reload.  I am going to try llama.cpp instead and report back

**Comment by awaescher** [comment]
I had this too and found a solution. Ollama reloads the model if the context window is different to the one that's loaded. So I used a fixed context window to keep the same model instance in use:

```yml
- name: ollama_chat/qwen3:30b-a3b
  system_prompt_prefix: "Code has always be written in english. /no_think"
  use_temperature: 0.7
  #reasoning_tag: think     # prevents reasoning thoughts in commit messages if reasoning is enabled
  extra_params:
    num_ctx: 30000          # fixed NumCtx prevents Ollama from un- & reloading models
    keep_alive: 30m         # prevents Ollama from unloading too soon
    max_tokens: 24000
    top_p: 0.8
    top_k: 20
    min_p: 0.0
    temperature: 0.7  
```

Two downsides:
 - you need to find a matching context window size for your workflow/repository
 - it's slowing down responses that would only require a smaller context window size
