### ISSUE TITLE
extra_body in aider.model.settings.yml is not used in OpenRouter

### ISSUE THREAD

**Issue by rstacruz** [Aider-AI/aider#3615]
### Issue

Hey all, just reposting a bug report [from Discord](https://discord.com/channels/1131200896827654144/1351029047072784455/1351029047072784455).

Setting `extra_params.extra_body.provider` doesn't seem to send these details to the provider. This has been observed in `openrouter/deepseek/*` models (it may happen in other providers/models, but this is just what we've tested).

For example, this should fail, because OpenAI doesn't provide deepseek... yet it will continue fine.

```yaml
# .aider.model.settings.yml
- name: openrouter/deepseek/deepseek-chat
  edit_format: diff
  extra_params:
    extra_body:
      provider:
        order: ["OpenAI"]
        allow_fallbacks: false
```

### Why this happens

I've good reason to believe that this is a LiteLLM issue (my debug notes follow in comments below). See: https://github.com/BerriAI/litellm/issues/8425

In the meantime, here's a workaround. According to the issue above, this is the last known version to work.

```sh
# when using aider dev version
pip install litellm==1.54.1

# when using aider installed via uv
uv tool run --from aider-chat pip install litellm==1.54.1
```

### Version and model info

Aider v0.78.0
Main model: openrouter/deepseek/deepseek-r1 with diff edit format, infinite output
Weak model: openrouter/google/gemini-2.0-flash-001
Git repo: .git with 364 files
Repo-map: disabled
