### ISSUE TITLE
Cloudlflare /@cf/deepseek-ai/deepseek-r1-distill-qwen-32b

### ISSUE THREAD

**Issue by sirganya** [Aider-AI/aider#3683]
### Issue

HI,

I'm attempting to use Cloudflare's worker AI with Aider. They have a deepseek-ai/deepseek-r1-distill-qwen-32b model available with a context window of 80k. Nice. They also have an openAI compatible api, nice.

When I start Aider and ask a question it responds well once but from then on it errors:

`Empty response received from LLM. Check your provider account?`

Sometimes I can get two responses before this happen. Sometimes it will return a number of empty responses before talking again.

I've been copying and pasting the r1 and reasoner configs from the aider source code and trying to find a recipe that works.

I've currently got a .aider.model.metadata.json like

```json
{
    "openai/@cf/deepseek-ai/deepseek-r1-distill-qwen-32b": {
        "max_tokens": 8192,
        "max_input_tokens": 64000,
        "max_output_tokens": 8192,
        "input_cost_per_token": 0.00000055,
        "input_cost_per_token_cache_hit": 0.00000014,
        "cache_read_input_token_cost": 0.00000014,
        "cache_creation_input_token_cost": 0.0,
        "output_cost_per_token": 0.00000219,
        "litellm_provider": "deepseek",
        "mode": "chat",
        "supports_assistant_prefill": true,
        "supports_prompt_caching": true
    }
}
```

and a .aider.model.setting.yml

```yaml
- name: "openai/@cf/deepseek-ai/deepseek-r1-distill-qwen-32b"
  edit_format: diff
  weak_model_name: openai/@cf/deepseek-ai/deepseek-r1-distill-qwen-32b
  use_repo_map: true
  examples_as_sys_msg: true
  extra_params:
    max_tokens: 8192
  caches_by_default: true
  use_temperature: false
  editor_model_name: openai/@cf/deepseek-ai/deepseek-r1-distill-qwen-32b
  editor_edit_format: editor-diff
 
```

any insights would be much appreciated.

### Version and model info

Aider: 0.80
Model:  deepseek-ai/deepseek-r1-distill-qwen-32b
Repo-map: using 4096 tokens, auto refresh
