### ISSUE TITLE
v0.80.0 openrouter/deepseek/deepseek-chat-v3-0324:free - wrong context size

### ISSUE THREAD

**Issue by tdobson** [Aider-AI/aider#3697]
### Issue

tdobson@tragicomix:~/Videos/dev/cavingcrew-hybrid-headless-react/hybrid-headless-front-end$ aider --model openrouter/deepseek/deepseek-chat-v3-0324:free --editor-model sonnet --auto-lint --no-attribute-committer --no-attribute-author --cache-prompts --architect  --lint-cmd "../magicLinter.sh" --test-cmd="npm run test" --no-stream

Aider v0.80.0
Model: openrouter/deepseek/deepseek-chat-v3-0324:free with architect edit format, prompt cache
Editor model: anthropic/claude-3-7-sonnet-20250219 with editor-diff edit format
Git repo: ../.git with 114 files
Repo-map: using 4096 tokens, files refresh
Note: in-chat filenames are always relative to the git working dir, not the current working dir.
Cur working dir: /home/tdobson/Videos/dev/cavingcrew-hybrid-headless-react/hybrid-headless-front-end
Git working dir: /home/tdobson/Videos/dev/cavingcrew-hybrid-headless-react

architect> /drop                                                                                                                                                                                                                   

Dropping all files from the chat session.

architect> /clear                                                                                                                                                                                                                  


architect> hi                                                                                                                                                                                                                      

                    
litellm.BadRequestError: OpenrouterException - This endpoint's maximum context length is 131072 tokens. However, you requested about 139125 tokens (8053 of text input, 131072 in the output). Please reduce the length of either 
one, or use the "middle-out" transform to compress your prompt automatically.

-- 

I'm not sure how to fix, or I would have submitted a PR.

Thanks for all your hard work.

### Version and model info

_No response_

**Comment by tdobson** [comment]
I've tried adding

- name: deepseek/deepseek-chat-v3-0324:free
  extra_params:
    max_tokens: 128000
    extra_body:
      provider:
        # Only use these providers, in this order
        order: ["Targon","Chutes"]
        # Don't fall back to other providers
        allow_fallbacks: true


to my .aider.conf.yml but without it fixing it.

**Comment by AkiraToya** [comment]
I also get this problem just now...

**Comment by mzit** [comment]
I don't know if it's related to this, but I'm getting an error .
The error message is: litellm.APIConnectionError: APIConnectionError: OpenrouterException - 'choices'. 
However, when I use openrouter/deepseek/deepseek-chat:free, I don't have any issues.

**Comment by josephleblanc** [comment]
Also broke for me, using json conf in .aider.model.metadata.json:
```json
    "openrouter/deepseek/deepseek-chat-v3-0324:free": {
        "max_tokens": 131000,
        "max_input_tokens": 131000,
        "max_output_tokens": 131000,
        "input_cost_per_token": 0.0,
        "output_cost_per_token": 0.0,
        "litellm_provider": "openrouter",
        "mode": "chat"
    }
```
Tried:
- Setting "max_tokens", "max_input_tokens", "max_output_tokens" to 0, still error. No effect.
- Removing the entire entry from json. No effect.

In .aider.models.settings.yml:
```yml
- name: openrouter/deepseek/deepseek-chat-v3-0324:free
  edit_format: diff
  use_repo_map: true
  reminder: sys
  examples_as_sys_msg: true
  extra_params:
    max_tokens: 131000
    # Only use these providers, in this order
    order: ["Targon", "Chutes"]
    # Don't fall back to other providers
    allow_fallbacks: false
    # Only use providers supporting all parameters
    require_parameters: true
  caches_by_default: true
```
Tried:
- Removing entire entry from conf. No effect.

This just broke this morning after updating to Aider v0.80.1. It was fine before update.
