### ISSUE TITLE
no idea why this happened. how to resolve? no commit messages generated

### ISSUE THREAD

**Issue by sprappcom** [Aider-AI/aider#3744]
### Issue

Failed to generate commit message!
Commit e290c63 (no commit message provided)

### Version and model info

latest aider

**Comment by GitMurf** [comment]
@sprappcom did you ever figure this out? I keep getting this erorr for commit messages and cannot figure it out for the life of me.

**Comment by huajiejin** [comment]
aider version: 0.83.2

I see the same issue when using `qwen3-32b-q8` with `llama.cpp`. Commit message generation fails.

```
Failed to generate commit message!
Commit b78b84e (no commit message provided)
You can use /undo to undo and discard each aider commit.
```

When using the `deepseek/deepseek-chat` model, it works as expected.

Here’s how I run qwen3:
```
HOST="127.0.0.1"
PORT=10001
MODEL_PATH="/path/to/qwen3/Qwen3-32B-Q8_0.gguf"
nohup llama-server \
  --model "$MODEL_PATH" \
  --host $HOST \
  --port $PORT \
  --prio 2 \
  --jinja \
  --reasoning-format deepseek \
  --n-gpu-layers -1 \
  --flash-attn \
  --split-mode row \
  --temp 0.7 \
  --top-k 20 \
  --top-p 0.8 \
  --min-p 0 \
  --ctx-size 20480 \
  --n-predict 32768 \
  --no-context-shift > "$LOG_STD" 2> "$LOG_ERR" &
```

.aider.model.settings.yml:
```
- name: openai/path/to/qwen3/Qwen3-32B-Q8_0.gguf
  system_prompt_prefix: "/no_think"
  use_temperature: 0.7
  extra_params:
    stream: true
    max_tokens: 20480
    top_p: 0.8
    top_k: 20
    temperature: 0.7
```

env:
```
export OPENAI_API_BASE=http://127.0.0.1:10001/v1
export OPENAI_API_KEY=none
```

Not sure if this is a model-specific or server compatibility issue.
