### ISSUE TITLE
Proposal: Add `attribute-co-authored-by` Option to Fix Unexpected Author/Committer Modification

### ISSUE THREAD

**Issue by ei-grad** [Aider-AI/aider#3788]
## Problem  

Currently, `aider` modifies author / committer name by appending `(aider)`, e.g., `John Doe (aider)`.
This behavior is non-standard, may break commit signature verification, and is generally unexpected for users.

Using Git's `Co-authored-by` trailer is a well-established alternative for attributing contributions without touching the user name.

A very similar issue already exists - #3270 (describing that GitHub will work better with such annotation), and Claude Code is also using `Co-authored-by` format (though, some want it to be disabled https://github.com/anthropics/claude-code/issues/617).

## Proposal  

Add `attribute-co-authored-by` option to `.aider.conf.yml`:  

```yaml
attribute-co-authored-by: true
```

Behavior:  
- If `true`:
  - Append `Co-authored-by: aider (<model>) <noreply@aider.dev>` to commit message
  - Disable behavior of other `attribute-` options, if they are not specified explicitly
- If `false` or unset:  
  - Rely on other `attribute-` options to keep the current behavior for backward compatibility

For context, currently available related options are:
```yaml
# Attribute aider code changes in the git author name (default: True)
attribute-author: true
# Attribute aider commits in the git committer name (default: True)
attribute-committer: true
# Prefix commit messages with 'aider: ' if aider authored the changes (default: False)
attribute-commit-message-author: false
# Prefix all commit messages with 'aider: ' (default: False)
attribute-commit-message-committer: false
```

Description of `attribute-author` option default value should be changed to mention relation with `attribute-co-authored-by`.

## Benefits  

- Respects user Git configuration  
- Compatible with commit signature verification  
- Aligns with Git conventions  
- Makes `aider` usage less intrusive in existing workflows  

## Notes  

Alternative: consider flipping the default (use `Co-authored-by` by default) in a future major release.
