### ISSUE TITLE
How to stop openrouter/deepseek/deepseek-r1 from thinking in thousands of tokens ?

### ISSUE THREAD

**Issue by GeorgeFlorian** [Aider-AI/aider#3803]
### Issue

How to stop openrouter/deepseek/deepseek-r1 from thinking in thousands of tokens ?
I input a prompt, it thinks in 100+ lines with code and all that shit and then it ask to edit files and then it again uses token to write the same code from the thinking process.

~/.aider.model.setting.yml:
```yml
name: openrouter/deepseek/deepseek-r1
  extra_params:
    top_p: 0.95
  use_temperature: 0.6
```
~/.aider.conf.yml
```yml
model: openrouter/deepseek/deepseek-r1
architect: true
editor-model: openrouter/anthropic/claude-3.5-sonnet
auto-accept-architect: false
auto-commits: false

cache-prompts: false
stream: true

dark-mode: true

lint: true

## Set the thinking token budget for models that support it (default: not set)
# thinking-tokens: 100
```
I have tried `thinking-tokens: 100`, it does not work.
I have tried `remove_reasoning: think` which is a setting that aider can't start with. (https://github.com/Aider-AI/aider/issues/3008#issuecomment-2635153135)

Is there no fix to this issue ? 
Should I just change from R1 ?

### Version and model info

Aider v0.81.1
Main model: openrouter/deepseek/deepseek-r1 with architect edit format, prompt cache, infinite output
Editor model: openrouter/anthropic/claude-3.5-sonnet with editor-diff edit format
Weak model: openrouter/deepseek/deepseek-chat
Git repo: .git with 75 files
Repo-map: using 4096 tokens, auto refresh

**Comment by LangLangBart** [comment]
> How to stop openrouter/deepseek/deepseek-r1 from thinking in thousands of tokens ?

If you mean by 'stop' that the reasoning should not be included in the response, then the following should work:

```yaml
- name: openrouter/deepseek/deepseek-r1
  extra_params:
    top_p: 0.95
    reasoning:
      # The model will still use reasoning, but it won’t be shown in the response.
      exclude: true
  use_temperature: 0.6
```

- Ref: https://openrouter.ai/docs/use-cases/reasoning-tokens

If you mean with 'stop' to not reason at all, then the `reasoning.effort` or `reasoning.max_tokens` did not help.

---

The `reasoning` field with `openrouter` appears to be quite new (around late February) according to the web archive, which might explain why it's not mentioned in the aider model settings documentation.

17/Feb/25 - include_reasoning
- https://web.archive.org/web/20250217150148/https://openrouter.ai/docs/use-cases/reasoning-tokens

26/Feb/25 - reasoning.exclude
- https://web.archive.org/web/20250226060225/https://openrouter.ai/docs/use-cases/reasoning-tokens
