### ISSUE TITLE
qwq 32B just considers the examples as part of the prompt that I give it

### ISSUE THREAD

**Issue by heaven00** [Aider-AI/aider#3805]
### Issue

I asked it to create test cases for a function using pytest parameterized, it's weird because it was working fine in an older version. 

I was able to find the get_factorial in  the example here https://github.com/Aider-AI/aider/blob/0c383dfb11dce7643d7e672efa5bfffa260bfe1b/aider/coders/editblock_prompts.py#L61

```
► THINKING

Okay, let me try to figure out what the user needs here. They mentioned working on a Git repository and provided
summaries of various files. The assistant is supposed to act as an expert code analyst, answering questions about
the code by either using the given file summaries or asking for full contents if needed.

Looking at the history, it seems there was some confusion where the user might have tried to ask a question but
got cut off. The last message from the user ends with "Change get_factorial()..." which is similar to an example
provided in the system prompt. Maybe they intended to ask how to modify a function called get_factorial in their
codebase, possibly wanting to switch it to use math.factorial instead of a custom implementation.

The assistant's previous response was cut off but started explaining steps for such a change. The user now might
be expecting that explanation to continue. However, looking at the provided file summaries, there isn't an
obvious get_factorial function mentioned in any of them. The files listed include stuff related to chat messages,
synthetic data generation, calendar event classification, async clients, etc., but nothing about factorial
calculations.

Hmm, this is a problem. Since none of the files mentioned have anything related to get_factorial, the assistant
can't proceed without more information. Maybe the user made a mistake in their question or perhaps there's a file
not listed here that contains that function. The correct approach would be to inform the user that based on the
provided summaries, no such function exists and ask for clarification or which specific files need to be checked.

Alternatively, if this is part of an example scenario from earlier (like the system prompt example), maybe the
user is testing how I handle questions outside the given context. In any case, I should respond by pointing out
that there's no get_factorial function in the provided files and ask for more details or the relevant code
snippet.

─────────────────────────────────────────────────────────────────────────────────────────────────────────────────
► ANSWER

It seems there might be some confusion as none of the files in your repository summaries reference a
get_factorial() function (the example you mentioned is from an unrelated context). Could you clarify which
specific file you want to modify, or what behavior you're trying to change?

For instance:

 • Are you referring to synthetic data generation logic?
 • Calendar event date/time calculations?
 • Something in the message classification pipeline?

Let me know so I can provide precise guidance!
```

### Version and model info

aider 0.81.3
aider-setitngs
```yaml
- name: ollama/qwen2.5-coder:32b
  edit_format: diff
  extra_params:
    max_tokens: 16384
    top_p: 0.8
    top_k: 20
    repetition_penalty: 1.05
    num_ctx: 16384
  use_temperature: 0.6
  reasoning_tag: think
  editor_edit_format: editor-diff
  editor_model_name: ollama/qwen2.5-coder:32b
- name: ollama/qwq:32b
  edit_format: diff
  extra_params:
    max_tokens: 16384
    top_p: 0.95
    top_k: 40
    presence_penalty: 0.1
    repetition_penalty: 1
    num_ctx: 16384
  use_temperature: 0.6
  reasoning_tag: think
  weak_model_name: "ollama/qwen2.5-coder:32b"
  editor_model_name: "ollama/qwen2.5-coder:32b"
```
