### ISSUE TITLE
deepseek coder base : default chat template is no longer allowed

### ISSUE THREAD

**Issue by theZappr** [Aider-AI/aider#3877]
### Issue

Hello everyone. 

First off: the aider project is awesome but I have hit a snag. I have read the docs quite a bit but I cant resolve this issue.

I am running local LLMs in vllm : deepseek coder-base and deepseek coder-instruct. These are just the 1.3b models for POC for now as I can get 40K tokens with those. The 6.7b only allows me 2K tokens. But ANYWAY

coder-instruct "works somewhat" with Aider on my repos, it keeps reporting 

`The LLM did not conform to the edit format. `

And so the code which is generated is often not making it to the file system.

coder-base doesn't work at all it just reports

```
litellm.BadRequestError: OpenAIException - As of transformers v4.44, default chat template is no longer allowed, so you must provide a chat template if the tokenizer does not define one.
```
I checked the downloaded huggingface LLMs that are mounted into the vllm container and coder-instrtuct does have a chat template but coder-base does not. This is by design, I understand. coder-base is not for general chat. 

I believe that Aider will work with deepseek coder-base if I was using the deepseek API and Key but as I am using vllm it exposes the openai API, Is it that Aider is then confused and expects a chat-capable LLM?

My model is named "openai/deepseek-coder-1-3b-base" in my .aida...yml/json files, as show below. Is there another config I need to add to get Aider to recognise the LLM is for code completion not chat? Or am I miles off?

Many thanks for any help :)

Config file parts :

```yaml
# .aider.model.settings.yml
- name: openai/deepseek-coder-1-3b-base
  extra_params:
    # model is mounted in vllm container as /model so:
    model: "openai/\/model"
    max_tokens: 20000

# ,aider.config.yml
model: openai/deepseek-coder-1-3b-base
openai-api-key: "dummy_key"
# etc...
```
and 

.aider.model.meta.json
```json
{
  "openai/deepseek-coder-1-3b-base": {
    "max_tokens": 20000,
    "max_input_tokens": 20000,
    "max_output_tokens": 20000,
    "input_cost_per_token": 0.0,
    "output_cost_per_token": 0.0,
    "litellm_provider": "openai",
    "supports_function_calling": true
  }
}
```
 

### Version and model info

Aider v0.82.2
Model: openai/deepseek-coder-1-3b-base with whole edit format
Git repo: .git with 52 files
Repo-map: using 1024 tokens, auto refresh
