### ISSUE TITLE
Can we get full support for local Qwen3 family?

### ISSUE THREAD

**Issue by fernandaspets** [Aider-AI/aider#3953]
### Issue

Can we get full support for local Qwen3 family? In the past I was able to manipulate the files to get Qwen2.5 working quite well. But why can't it be more simple like just serve the model with vllm and a one liner just like with the major providers? for vllm, I want to just launch aider with something like aider vllm_local/Qwen3/Qwen3-235B... or for llamacpp aider llamacpp/Qwen3/Qwen3-32B-FP8. And then can we get aider optimized for using locally hosted Qwen3 family? I mean cuz I was literally spending hours in the docs and config files to get local Qwen2.5 to work well before. The whole point of using aider over Codex and and Claude Code for me is to run 100% independent of theses closed source companies

**Comment by GaloisField2718** [comment]
Is it not working to setup the OPENAI_API variable with your endpoint (like: http://127.0.0.1:8000/v1/completions) and configure the model with `.aider.model.meta`?
Like: 
```
- name: vllm_local/Qwen3/Qwen3-235B
  edit_format: diff
  use_repo_map: true
  extra_params:
    max_tokens: 32000
    top_p: 0.95
    temperature: 0.7
  editor_model_name: vllm_local/Qwen3/Qwen3-235B
  editor_edit_format: editor-diff
```
