### ISSUE TITLE
Custom API and key give a connection error

### ISSUE THREAD

**Issue by EchoZhaoH** [Aider-AI/aider#4059]
### Issue

```yml
openai-api-base: https://localapi
openai-api-key: xxxx
model: openai/xxx
```
Running Aider gives the following error with the above config, but curl works.
<img width="591" alt="Image" src="https://github.com/user-attachments/assets/6bc3eb79-4934-4201-8df6-4c636d1893a0" />
