### ISSUE TITLE
Add claude 4

### ISSUE THREAD

**Issue by jdanbrown** [Aider-AI/aider#4063]
### Issue

Released today (2025-05-22) 🎉 
- https://www.anthropic.com/news/claude-4

Please include the openrouter models in addition to the usual anthropic/bedrock/etc. ones :)
- https://openrouter.ai/anthropic/claude-sonnet-4
- https://openrouter.ai/anthropic/claude-opus-4

**Comment by y0ug** [comment]
In the meantime you can create a file  ` .aider.model.settings.yml` in your `$HOME`,  project, etc... 

[Advanced model settings | aider](https://aider.chat/docs/config/adv-model-settings.html)

[aider/aider/resources/model-settings.yml at main · Aider-AI/aider](https://github.com/Aider-AI/aider/blob/main/aider/resources/model-settings.yml#L187)

```
- name: anthropic/claude-4-sonnet-20250514
  overeager: true
  edit_format: diff
  weak_model_name: anthropic/claude-3-5-haiku-20241022
  use_repo_map: true
  examples_as_sys_msg: true
  extra_params:
    extra_headers:
      anthropic-beta: prompt-caching-2024-07-31,pdfs-2024-09-25,output-128k-2025-02-19
    max_tokens: 64000
  cache_control: true
  editor_model_name: anthropic/claude-3-7-sonnet-20250219
  editor_edit_format: editor-diff
  accepts_settings: ["thinking_tokens"]
```
